name: Pull Request Tests
on:
  pull_request:
    branches:
      - main
jobs:
    build:
      name: Build web app
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Node modules
        run: npm install
      - name: Build web app
        run: npm run build
